### ISSUE TITLE
Could I take the name of the library from npm?

### ISSUE THREAD

**Issue by VladimirCores** [callumlocke/wire#7]
Hello @callumlocke, I'm developing a library to manage data and events distribution in web/mobile applications - its called [wire](https://github.com/WiresWare/wire_ts). Originally I wrote it in Dart but recently ported on TypeScript as well. So I'm asking could you please release the name `wire` from npm or rename it to something a little bit different? Thanks.

**Comment by callumlocke** [comment]
Hey sorry just saw this. Sorry but I've actually recently restarted dev on this project and I'm planning to release a new version to npm soon. I know the current published version is very outdated, but I'm currently working on a new rewrite as a dual deno/node package, and then plan to publish to npm again.

Your library looks interesting. There's always a chance I might not see this project through, so feel free to ask me again in a few months if dev on this repo seems to have stalled, as I don't want to squat the name if I'm not using it.

**Comment by VladimirCores** [comment]
Hello @callumlocke! How are you doing? More than year and a half ago I was asking you about releasing the name of the library. So, could you release the name `wire`?

**Comment by VladimirCores** [comment]
@callumlocke do you have resolution on my request?
